# Generated by Django 4.1.3 on 2022-11-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('sent', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
