# Generated by Django 4.1.3 on 2022-11-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('test_result', models.CharField(choices=[('P', 'POSITIVE'), ('N', 'NEGATIVE')], default='N', max_length=1)),
                ('status', models.CharField(choices=[('R', 'Retired'), ('S', 'Sold'), ('B', 'Breeder'), ('K', 'Kid')], max_length=1)),
                ('availability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Pending'), ('S', 'Coming Soon')], default='N', max_length=1)),
                ('price', models.IntegerField(default=0)),
                ('comments', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Buck',
            fields=[
                ('goat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goat.goat')),
                ('gender', models.CharField(choices=[('B', 'Buck'), ('W', 'Wether')], default='B', max_length=1)),
            ],
            bases=('goat.goat',),
        ),
        migrations.CreateModel(
            name='Doe',
            fields=[
                ('goat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goat.goat')),
                ('bred_status', models.CharField(choices=[('B', 'Bred'), ('O', 'Open')], default='O', max_length=1)),
                ('due', models.DateField(blank=True, null=True, verbose_name='estimated due date')),
                ('bred_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mate', to='goat.buck')),
            ],
            bases=('goat.goat',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='photo album')),
                ('description', models.CharField(max_length=50)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goat.goat')),
            ],
        ),
        migrations.AddField(
            model_name='goat',
            name='dam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dkid', to='goat.doe'),
        ),
        migrations.AddField(
            model_name='goat',
            name='dd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ddgrandkid', to='goat.doe'),
        ),
        migrations.AddField(
            model_name='goat',
            name='ds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dsgrandkid', to='goat.buck'),
        ),
        migrations.AddField(
            model_name='goat',
            name='sd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sdgrandkid', to='goat.doe'),
        ),
        migrations.AddField(
            model_name='goat',
            name='sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skid', to='goat.buck'),
        ),
        migrations.AddField(
            model_name='goat',
            name='ss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssgrandkid', to='goat.buck'),
        ),
    ]
