# Generated by Django 4.1.3 on 2022-11-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat', '0002_alter_goat_options_alter_goat_test_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goat',
            name='status',
            field=models.CharField(choices=[('RETIRED', 'Retired'), ('SOLD', 'Sold'), ('BREEDER', 'Breeder'), ('KID', 'Kid')], default='KID', max_length=7),
        ),
    ]
