# Generated by Django 4.1.3 on 2022-11-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat', '0003_alter_goat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goat',
            name='availability',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('PENDING', 'Pending'), ('SOON', 'Coming Soon')], default='NO', max_length=7),
        ),
    ]
