# Generated by Django 4.1.3 on 2022-11-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat', '0008_alter_goat_dam_alter_goat_sire'),
    ]

    operations = [
        migrations.AddField(
            model_name='doe',
            name='gender',
            field=models.CharField(default='DOE', max_length=3),
        ),
    ]
