# Generated by Django 4.1.3 on 2022-11-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat', '0009_doe_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doe',
            name='gender',
            field=models.CharField(choices=[('DOE', 'Doe')], default='DOE', max_length=3),
        ),
    ]
